version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: cowork_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coworking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cowork_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api-gateway:
    build: ./app/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - booking-service

  booking-service:
    build: ./app/booking-service
    depends_on:
      - postgres
      - rabbitmq

  email-service:
    build: ./app/email-service
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
